# Generated by Django 6.0.1 on 2026-02-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
