# Generated by Django 6.0.1 on 2026-02-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('gentlemen', 'gentlemen'), ('ladies', 'ladies'), ('neutral', 'neutral')], default='neutral', max_length=20),
        ),
    ]
