# Generated by Django 6.0.1 on 2026-02-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_usertheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('benito', 'Benito'), ('earthy', 'Earthy'), ('marty_supreme', 'Marty Supreme'), ('lanacore', 'Lanacore'), ('italian_summer', 'Italian Summer')], default='default', max_length=20),
        ),
    ]
