# Generated by Django 6.0.1 on 2026-02-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_usertheme_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertheme',
            name='theme',
        ),
        migrations.AddField(
            model_name='usertheme',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
